"""
Author: Sid Tandale
Program: Map Generator
Description: Generates a random grid map with obstacles and saves to a text file.
"""

# Imports
import numpy as np
import random

# Map generation function
def generate_map(filename="map_data.txt", size=50, density=0.30):
    """
    Generates a random grid map and saves to a text file.
    size: Size of the grid (size x size)
    density: Fraction of cells that are obstacles
    0 = free cell, 1 = obstacle
    """

    # Basic validation
    if size <= 5:
        raise ValueError("Map size must be greater than 5.")

    # Generate grid
    grid = np.zeros((size, size), dtype=int)
    num_obstacles = int(size * size * density)

    # Place obstacles randomly
    # For loop generated by ChatGPT
    for _ in range(num_obstacles):
        x, y = random.randint(0, size - 1), random.randint(0, size - 1)
        grid[y, x] = 1

    # Ensure start and goal are free
    grid[0, 0] = 0
    grid[size-1, size-1] = 0

    # Save to file
    np.savetxt(filename, grid, fmt='%d')
    print(f"Generated {size}x{size} map with {density*100:.0f}% obstacles.")
    print(f"Saved as {filename}")

    return grid


if __name__ == "__main__":
    generate_map()